project:
  groupId: com.mycompany.app
  artifactId: my-app
  version: 0.1
java.version: 1.8

# Space settings
space:
  name: demo

# Database and hibernate settings
db:
  name: demo-db
  url: jdbc:hsqldb:hsql://localhost/demo-db
  user: sa
  password: ""
  driver:
    class: org.hsqldb.jdbc.JDBCDriver
    groupId: org.hsqldb
    artifactId: hsqldb
    version: 2.3.2
hibernate:
  version: 5.2.18.Final
  dialect: org.hibernate.dialect.HSQLDialect